---
title: "ACPD filter"
output: html_document
---
```{r}
pacman::p_load(httr, readr, stringr, dplyr, data.table, dtplyr)
arlington_api_key = '140c712ce0aaf752160366975a7fa1cca8c81445'

crime_incidence = str_c('https://api.data.arlingtonva.us/api/v2/',
                        'datastreams/POLIC-INCID-LOG-19589/data.csv/?auth_key=',
                        arlington_api_key) %>%
  GET() %>%
  content(as = 'text', encoding = 'UTF-8') %>%
  read_csv() %>%
  data.table()
```

```{r}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(docstring, purrr, stringi, stringr, lubridate, geosphere, dplyr, data.table, dtplyr)
```


```{r}
crime_type <-  c('DRUNK', 'DUI', 'ASSAULT', 'POSSESSION', 'SEXUAL', 'DISORDERLY' )
```
```{r}
report <- (crime_incidence)
head(report)
```
```{r}
crime_report <- report %>%
  mutate(crime_type = str_detect(string = offenseDsc,
                                  pattern =
                                    '(DRUNK|DUI|ASSAULT|POSSESSION|SEXUAL|DISORDERLY)'))
```
```{r}
head(crime_report)
```
```{r}
compute_distance_from_hq_in_kim <- function(lon, lat) {
  output = distm(x = c(lon, lat),
                 y = c(-77.0950, 38.8872),
                 fun = distVincentyEllipsoid) / 1000
  return(value = output)
}
```
```{r}
crime_type <- report %>%
  mutate(nearby = map2_dbl(.x = longitudeCrd,
                          .y = latitudeCrd,
                          .f = compute_distance_from_hq_in_kim) <= 0.804672)
View(crime_type)
table(crime_type$nearby)
```



Nightlife is defined as:
  #' 
  #' - Friday between 21:00 - 24:00
  #' 
  #' - Saturday between 00:00 - 03:00 and 21:00 - 24:00
  #' 
  #' - Sunday between 00:00 - 03:00 and 21:00 - 24:00
  #' 
  #' - Monday between 00:00 - 03:00
  #' 
  #' - Saint Patrick's Day (03-17) between 21:00 - 24:00
  #' 
  #' - Day after Saint Patrick's Day (03-17) between 00:00 - 03:00
  #' 
  #' - 5 de mayo (05-05) between 21:00 - 24:00
  #' 
  #' - Day after 5 de mayo (05-06) between 00:00 - 03:00
  #' 


```{r}
Friday <- function(dt) {
  if (wday(x = dt) == )
}
```



















