---
title: "incidents_filtered"
author: "Kateryna Savchyn"
date: "6/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install packages
```{r install packages, message=FALSE}
for (pkg in c("DBI", "RPostgreSQL", "maditr", "geosphere", 'purrr', 'dplyr', 'stringr')) {
  library(pkg, character.only = TRUE)
}
```

## Helper Functions
```{r read-in incidents}
get_incidents = function() {
  conn <- dbConnect(drv = PostgreSQL(),
                    dbname = "acpd",
                    host = "postgis",
                    port = "5432",
                    user = Sys.getenv("db_userid"),
                    password = Sys.getenv("db_pwd"))
  output <- dbReadTable(conn = conn,
                       name = 'incidents') %>%
    data.table()
  on.exit(dbDisconnect(conn = conn))
  return(value = output)
}

# outputs km between location and clarendon metro as origin
compute_distance_from_hq_in_km <- function(lon, lat) {
  output = distm(x = c(lon, lat),
                 y = c(-77.0950, 38.8872),
                 fun = distVincentyEllipsoid) / 1000
  return(value = output)
}
```

## Function to Pull, Filter, and Write Incidents data
```{r write out filtered incidents}

refresh_filtered_incidents <- function(){
  # add stop block that throws error if table doesn't exist
  conn <- dbConnect(drv = PostgreSQL(),
                    dbname = "acpd",
                    host = Sys.getenv("host"),
                    port = Sys.getenv("port"),
                    user = Sys.getenv("db_userid"),
                    password = Sys.getenv("db_pwd"))
  acpd_data <- dbReadTable(conn = conn,
                       name = 'incidents')
  
  acpd_filtered <- acpd_data %>%
    mutate(nearby = map2_dbl(.x = longitude,
                             .y = latitude,
                             .f = compute_distance_from_hq_in_km) <= 8.04672) %>%
    mutate(day = weekdays(as.Date(acpd_data$start)), 
           hour = as.numeric(format(as.POSIXct(strptime(acpd_data$start, "%Y-%m-%d %H:%M:%S")), format = "%H"))) %>%
    mutate(crime_type = str_detect(string = description,
                                   pattern ='(DRUNK|DUI|ASSAULT|POSSESSION|SEXUAL|DISORDERLY)')) %>%
  
      ## Filter for Time: party time = THURS-SUN 9PM-5AM (21:24, 1:5) but also include Cinco de Mayo and St. Patricks Day
      filter(day %in% c("Thursday", "Friday", "Saturday", "Sunday") | grepl(paste(c("05-05 | 05-06 | 03-17"), collapse = "|"), start)) %>% 
      filter(hour %in% c(1:5,21:24)) %>%
      ## Filter for Location: filter to anything within a 5 mile radius ~ 8 km radius from metro origin
      filter(nearby == TRUE) %>%
      ## Filter for crime-type
      filter(crime_type == TRUE)

  acpd_filtered$nearby <- acpd_filtered$crime_type <- NULL
  
  # write out the output to DB
  dbWriteTable(con = conn,
                   name = 'incidents_filtered',
                   value = acpd_filtered,
                   row.names = FALSE)
  on.exit(expr = dbDisconnect(conn = conn))
}

#refresh_filtered_incidents()

```
