---
title: "Analysis"
author: "José Bayoán Santiago Calderón"
date: "2019-07-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading the data

```{r}
pacman::p_load(maditr, lubridate, here, tidyverse, rio, janitor, plyr)
```

```{r}
ari_names <- function(rest_name) {
  if (str_detect(string = rest_name,
                 pattern = "(?i)(Los Tios|Los Tios Grill)")) {
    "Los Tios"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(ba ba|baba|baba bar|ba ba bar)")) {
    "BA BA"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(buena|vida)")) {
    "Buena Vida"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(liberty tavern)")) {
    "LT"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(bracket|brakett|BR)")) {
    "BR"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(don tito|DT)")) {
    "DT"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(GOAT|G\\.O\\.A\\.T\\.?|^GT$)")) {
    "GT"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(freddie)")) {
    "Freddie's Beach Bar & Restaurant"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(fredrico|federico)")) {
    "Federico Ristorante Italiano"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(four courts)")) {
    "Ireland's Four Courts"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(mexicali|^MB$)")) {
    "MB"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(sullivan)")) {
    "O'Sullivan's Irish Pub"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(punch bowl|PBS)")) {
    "PBS"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(rhodeside)")) {
    "Rhodeside Grill"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(samuel becket)")) {
    "Samuel Beckett's Irish Gastro Pub"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(celtic)")) {
    "The Celtic House Irish Pub & Restaurant"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(spirits of|spirit of|76)")) {
    "x76"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(ttt|mexican diner)")) {
    "TTT"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(whitlow|WT)")) {
    "WT"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(william jeffrey)")) {
    "William Jeffrey's Tavern"
  } else if (str_detect(string = rest_name,
                        pattern = "(?i)(wilson hardware|wh)")) {
    "WH"
  } else {
    rest_name
  }
}
```

```{r}
ari_restaurants <- here::here("data", "acpd", "original", "ARI Nightlife Detail Logs", "ARI Restaurant List.xlsx") %>%
  import(setclass = "data.table",
         col_types = c("text", "text", "skip", "skip", "skip", "skip", "text",
                       "date", "skip", "skip", "skip", "skip", "skip", "skip",
                       "skip", "skip", "skip", "skip", "skip", "skip",
                       "skip", "skip", "skip", "skip", "skip", "skip",
                       "skip", "skip")) %>%
  clean_names() %>%
  dt_filter(!is.na(x = ari_accreditation_date) &
              address != "1101 S Joyce St") %>%
  dt_mutate(risk = ordered(x = risk, levels = c("Low", "Med", "High")),
            restaurant = map_chr(.x = restaurant, .f = ari_names) %>%
              make_clean_names() %>%
              str_remove_all(pattern = "_2$")) %>%
  dt_arrange(risk, restaurant) %>%
  unique()
  

fwrite(x = ari_restaurants,
       file = here::here("data", "acpd", "working","ari_restaurants.tsv"),
       sep = "\t")

sim <- fread(input = here::here("data", "acpd", "working", "Similarity_Matrix", "raw_similarity_scores_ari.csv")) %>%
  clean_names() %>%
  dt_select(!str_detect(string = names(x = .), pattern = "_2$")) %>%
  group_by(restaurant) %>%
  slice(1L) %>%
  unique() %>%
  dt_mutate(restaurant = map_chr(.x = restaurant, .f = ari_names) %>%
              make_clean_names()) %>%
  setcolorder(neworder = c(sort(setdiff(x = names(x = .),
                                        y = "restaurant")), "restaurant")) %>%
  dt_arrange(restaurant)
# setdiff(ari_restaurants$restaurant, sim$restaurant)
ari_restaurants <- ari_restaurants %>%
  dt_filter(restaurant %in% sim$restaurant)

in_data <- map_lgl(.x = sim$restaurant,
                   .f = function(restaurant) restaurant %in% ari_restaurants$restaurant) %>%
  which()

sim <- sim %>%
  dt_filter(in_data) %>%
  dt_select(c(in_data, ncol(x = .))) %>%
  setNames(nm = c(.$restaurant, "restaurant"))


find_pair <- function(x) {
  idx <- which(ari_restaurants$restaurant == x)
  risk_0 <- ari_restaurants$risk[idx]
  ari_date_0 <- ari_restaurants$ari_accreditation_date[idx]
  candidates <- ari_restaurants %>%
    # filter(risk %in% risk_0) %>%
    dt_filter((ari_accreditation_date - ari_date_0) >= 30L)
  if (nrow(x = candidates) == 0L) {
    output <- data.table()
  } else if (nrow(x = candidates) == 1L) {
    y <- candidates$restaurant[1]
    idx <- grep(x = ari_restaurants$restaurant, pattern = y)
    ari_date_1 <- ari_restaurants$ari_accreditation_date[idx]
    output <- data.table(x = x, y = y, start_date = ari_date_0, end_date = ari_date_1)
  } else {
    # Due to some weird stuff in the distance matrix
    cols_idx <- grep(x = sim$restaurant, pattern = x)
    idx <- sim %>%
      filter(str_detect(string = restaurant,
                        pattern = x)) %>%
      head(n = 1L) %>%
      dt_select(candidates$restaurant) %>%
      order() %>%
      getElement(name = 1L)
    ari_date_1 <- ari_restaurants$ari_accreditation_date[idx]
    output <- data.table(x = x, y = ari_restaurants$restaurant[idx],
                         start_date = ari_date_0, end_date = ari_date_1)
  }
  output
}

for (i in 1:length(ari_restaurants$restaurant)) {
  print(i)
  find_pair(ari_restaurants$restaurant[i])
}



codebook <-  here::here("data", "acpd", "original", "ARI Nightlife Detail Logs", "Restaurant List & Acronyms.xlsx") %>%
  import(setclass = "data.table") %>%
  remove_empty(which = "rows") %>%
  clean_names() %>%
  setNames(nm = c("restaurant", "id"))
# setdiff(ari_restaurants$restaurant, chk$x)
# setdiff(ari_restaurants$restaurant, chk$y)

chk <- map_df(.x = ari_restaurants$restaurant,
              .f = find_pair)
# names(ari_restaurants)
# names(sim)

dt <- fread(input = here::here("data", "acpd", "working", "Clarendon_details", "clarendon_clean_03.csv")) %>%
  clean_names() %>%
  dt_select(-c(x1, index)) %>%
  setnames(old = "establishment", new = "restaurant") %>%
  dt_mutate(date = as_date(date),
            restaurant = map_chr(.x = restaurant, .f = ari_names) %>%
              make_clean_names() %>%
              str_remove_all("_\\d+$")) %>%
  dt_filter(restaurant %in% ari_restaurants$restaurant)
  # dt_filter(restaurant %in% union(chk$x, chk$y))

arg <- unique(dt$restaurant)

unique(dt$restaurant)


magic <- function(idx) {
  x <- chk$x[idx]
  y <- chk$y[idx]
  d0 <- chk$start_date[idx]
  d1 <- chk$end_date[idx]
  per_of_int <- interval(start = d0, end = d1)
  subtbl <- dt %>%
    data.table() %>%
    dt_filter((restaurant %in% c(x, y)) &
                date %within% per_of_int)
  subtbl[, count := sum(num_cfs), by = c("restaurant")]
  subtbl <- subtbl %>%
    dt_filter(main_category == "Identification") %>%
    dt_select(restaurant, count) %>%
    unique()
  x <- subtbl$count[subtbl$restaurant == x]
  y <- subtbl$count[subtbl$restaurant == y]
  if (is_empty(x = x)) {
    x <- 0L
  }
  if (is_empty(x = y)) {
    y <- 0L
  }
  data.table(x = if_else(condition = is_empty(x = x), true = 0L, false = x),
             y = if_else(condition = is_empty(x = y), true = 0L, false = y))
}

x <- map_df(.x = 1:nrow(chk), magic)

sort(union(chk$x,chk$y))
with(x,
     t.test(x = x, y = y, paired = TRUE, conf.level = 0.9))
?t.test

chk <- map_df(.x = ari_restaurants$restaurant,
              .f = find_pair) %>%
  mutate(period = end_date - start_date) %>%
  filter(abs(period) >= 28) %>%
  dt_mutate(x = mapvalues(x, from = codebook$restaurant,
                          to = codebook$id,
                          warn_missing = FALSE)) %>%
  dt_mutate(x = recode(x,
                       "Lebanese Taverna" = "LT",
                       "Courthaus Social" = "CS",
                       "Spirits of ‘76" = "76",
                       "O’Sullivan’s Irish Pub" = "OS",
                       "Punch Bowl Social Arlington" = "PBS",
                       "The G.O.A.T" = "GT",
                       "Whitlow's On Wilson" = "WT",
                       "Wilson Hardware Kitchen & Bar" = "WH",
                       "Ambar" = "AMBAR",
                       "Bracket Room" = "BR",
                       "BA BA" = "BABA"
                       ),
            y = recode(y,
                       "Lebanese Taverna" = "LT",
                       "Courthaus Social" = "CS",
                       "Spirits of ‘76" = "76",
                       "O’Sullivan’s Irish Pub" = "OS",
                       "Punch Bowl Social Arlington" = "PBS",
                       "The G.O.A.T" = "GT",
                       "Whitlow's On Wilson" = "WT",
                       "Wilson Hardware Kitchen & Bar" = "WH",
                       "Ambar" = "AMBAR",
                       "Bracket Room" = "BR",
                       "BA BA" = "BABA"
                       ))
selected <- with(chk, unique(c(x, y)))

zz <- data.table(restaurant = selected)



magic <- function()

union(chk$x, chk$y) %>%
  sort()

library(snakecase)

z <- unique(dt$restaurant)
setdiff(selected, z)
chk2 = merge(x = zz, y = dt, by = "restaurant")

good_ones <- unique(chk2$restaurant)
```
