---
title: "ari_boundary_map"
author: "Kateryna Savchyn"
date: "6/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r helpers}
make_circles <- function(centers, radius, nPoints = 100){
    # centers: the data frame of centers with ID
    # radius: radius measured in kilometer
    #
    meanLat <- mean(centers$latitude)
    # length per longitude changes with lattitude, so need correction
    radiusLon <- radius /111 / cos(meanLat/57.3) 
    radiusLat <- radius / 111
    circleDF <- data.frame(ID = rep(centers$ID, each = nPoints))
    angle <- seq(0,2*pi,length.out = nPoints)

    circleDF$lon <- unlist(lapply(centers$longitude, function(x) x + radiusLon * cos(angle)))
    circleDF$lat <- unlist(lapply(centers$latitude, function(x) x + radiusLat * sin(angle)))
    return(circleDF)
}

compute_distance_from_hq_in_km <- function(lon, lat) {
  output = distm(x = c(lon, lat),
                 y = c(-77.0950, 38.8872),
                 fun = distVincentyEllipsoid) / 1000
  }
```


```{r ari missing, message=FALSE}
# geocode missing restaurants
for (pkg in c("DBI", "RPostgreSQL", "maditr", "geosphere", "stringr", "httr", "dplyr", "sf", "ggmap", "tidyverse",  "osmdata", "ggplot2", "sf")) {
  library(pkg, character.only = TRUE)
  }

not_accredited <- data.frame(name = c('Celtic House','Lebanese Taverna-Pentagon Row','Lebanese Taverna-Westover'), adr = c('2500 Columbia Pike, Arlington, VA 22204', '1101 S Joyce St, Arlington, VA 22202', '5900 Washington Blvd, Arlington, VA 22205'), status='Not Accredited in API layer') 
missing_in_api <- data.frame(name = c('Fiona\'s Irish Pub','G.O.A.T','The Local Oyster', 'Punch Bowl Social',
'Rebellion On The Pike'), adr = c('567 23rd St S, Arlington, VA 22202', '3028 Wilson Blvd, Arlington, VA 22201', '4238 Wilson Blvd, Arlington, VA 22203', '4238 Wilson Blvd Ste. 1180, Arlington, VA 22203', '2900 Columbia Pike, Arlington, VA 22204'), status = "Not present in API layer")

# have to improve the below 
missing <- rbind(not_accredited, missing_in_api)
missing$adr_mod <- gsub("[[:space:]]", "+", missing$adr) 
missing$adr_mod <- str_replace(missing$adr_mod,"[+]Arlington", "Arlington")
missing$adr_mod <- str_replace(missing$adr_mod,"[+]VA[+]", "VA ")
missing$adr_mod <- str_replace(missing$adr_mod, " ", ",")

key <- 'dG2GaXJQ2x78GVhbJL2IqJPM4CVtZz25' #Sys.getenv('mapquest_key') <- not working

missing_final <- missing %>% dt_mutate(urls = paste0('http://www.mapquestapi.com/geocoding/v1/address?key=dG2GaXJQ2x78GVhbJL2IqJPM4CVtZz25&location=',adr_mod))

for (i in 1:length(missing_final$name)) {
  missing_final$lat[i] <- content(GET(missing_final$urls[i]))$results[[1]]$locations[[1]]$displayLatLng$lat
  missing_final$lng[i] <- content(GET(missing_final$urls[i]))$results[[1]]$locations[[1]]$displayLatLng$lng
}

```

```{r ari api data}
# pull in all ARI API restaurants
ari_restaurants <-  st_read(dsn = "https://opendata.arcgis.com/datasets/2dc91350ea6f4bffb65ece8730b7fcca_0.geojson") %>%
                    data.table()

ari_restaurants <- ari_restaurants[!is.na(ari_restaurants$ARIAccredit),]

ari_restaurants$geometry <- as.character(ari_restaurants$geometry)
ari_restaurants$lng <- substr(ari_restaurants$geometry,3,13)
ari_restaurants$lat <- substr(ari_restaurants$geometry,20,32)
ari_restaurants$lat <- gsub("[[:space:]]", "", ari_restaurants$lat) 
ari_restaurants$lat <- gsub(",", "", ari_restaurants$lat) 
```

```{r merge api w missing}
ari_restaurants <- ari_restaurants[,c('Restaurant', 'Address', 'lng','lat')]
ari_restaurants$status <- 'Included in API layer'

missing_final <- missing_final[,c('name','adr','lng','lat','status')]

names(ari_restaurants) <- names(missing_final)

complete <- rbind(ari_restaurants,missing_final)
complete$lon <- as.numeric(complete$lng)
complete$lat <- as.numeric(complete$lat)
```

```{r map plot}
# plot on map w 0.5 mile decision boundary
arlington.box <- getbb("arlington county")
arlington.map <- get_map(location = arlington.box, source="stamen", maptype="watercolor", crop = TRUE)
arlington.boundary <- getbb("arlington county", format_out = "polygon") %>%
                      as.tibble() %>%
                      rename(longitude = `V1`, latitude = `V2`)
arlington.rests <- complete %>% as.tibble()

```

```{r boundary}
data = data.frame(
    ID = as.numeric(1),
    longitude = as.numeric(-77.0950),
    latitude = as.numeric(38.8872)
)

myCircles1 <- make_circles(data, 0.804672) #circles in km - show .5 mile boundary from last year
myCircles2 <- make_circles(data, 1.60934)  #1 mile radius 
myCircles3 <- make_circles(data, 4.82803) #3 mile radius

ggmap(arlington.map) +
  geom_polygon(data = arlington.boundary, aes(x = longitude, y = latitude), colour = "black", size = 1, alpha = 0.1) + 
  geom_point(data = arlington.rests, aes(x = lon, y = lat, fill = status), size = 3, pch = 21)  +
  scale_fill_manual(values=c("Included in API layer"="blue","Not Accredited in API layer"="pink", "Not present in API layer" = "orange")) +
  #geom_text(data = arlington.rests, aes(label=ifelse(outside = TRUE,name),size = 3, hjust=0, vjust=0) +
  geom_polygon(data = myCircles1, aes(lon, lat, group = ID), color = "firebrick1", size = 1.5, alpha = 0) +
  geom_polygon(data = myCircles2, aes(lon, lat, group = ID), color = "firebrick3", size = 1, alpha = 0) + 
  geom_polygon(data = myCircles3, aes(lon, lat, group = ID), color = "firebrick4", size = 1, alpha = 0) +
  labs(x = "Longitude",y = "Latitude") + 
  ggtitle("ARI Map Boundary and Participants")  + theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.text=element_text(size=12))

ggsave("~/acpd/figures/ari_boundary.png")
```

```{r table}
arlington.table <- complete %>% 
                  dt_mutate(nearby = map2_dbl(.x = lon,
                                              .y = lat,
                                              .f = compute_distance_from_hq_in_km) <= 0.804672) %>%
                  dt_select(-lng)
arlington.table <- arlington.table[,c('name', 'adr','status','lat','lon','nearby')]

ari_path <- here("data", "acpd", "working", "ari_boundary_info.csv")

if (!file.exists(ari_path)){
  write.table(arlington.table, ari_path, sep = ';')
}

```



