---
title: "licenses_geo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r }

for (pkg in c("lubridate", "purrr", "maditr", "here", "RPostgreSQL", "stringr", "sf","geosphere","httr","assertthat")) {
  library(pkg, character.only = TRUE)
}

geocode <- function(address) {
  response <- str_c("http://www.mapquestapi.com/geocoding/v1/address?key=dG2GaXJQ2x78GVhbJL2IqJPM4CVtZz25&location=",
                    str_replace_all(string = address, pattern = "\\s+", replacement = "+") %>%
                      str_replace(pattern = "\\+Arlington,\\+VA\\+", replacement = "Arlington,VA")) %>%
    GET()
  assert_that(status_code(x = response) == 200L)
  response %>%
    content() %>%
    getElement(name = "results") %>%
    getElement(name = 1L) %>%
    getElement(name = "locations") %>%
    getElement(name = 1L) %>%
    getElement(name = "displayLatLng") %>%
    unlist() %>%
    t() %>%
    data.table()
}


#Connect to the host
conn <- dbConnect(drv = PostgreSQL(),
                  host = "postgis_1",
                  port = 5432L,
                  dbname = "acpd",
                  user = Sys.getenv(x = "db_userid"),
                  password = Sys.getenv(x = "db_pwd"))


#Read in our layer
ari_restaurants <- st_read(dsn = conn, layer = "ari_restaurants")

#Get coordinates for restaurants
geometry <-st_coordinates(ari_restaurants) %>%
  data.table() %>%
  dt_mutate(OBJECTID = ari_restaurants$OBJECTID) %>%
  merge(y = ari_restaurants) %>%
  dt_select(-c(OBJECTID, geometry))

compute_distance_from_hq_in_km <- function(lon, lat) {
  distm(x = c(lon, lat),
        y = c(-77.0950, 38.8872),
        fun = distVincentyEllipsoid) / 1000
}

#not_accredited <- data.frame(name = c('Celtic House','Lebanese Taverna-Pentagon Row','Lebanese Taverna-Westover'), adr = c('2500 Columbia Pike, #Arlington, VA 22204', '1101 S Joyce St, Arlington, VA 22202', '5900 Washington Blvd, Arlington, VA 22205'), reason='not accredited in api')
missing_in_api <- data.table(Restaurant = c("Fiona's Irish Pub",
                                            "G.O.A.T",
                                            "The Local Oyster",
                                            "Punch Bowl Social",
                                            "Rebellion On The Pike",
                                            "Wilson Hardware"),
                             Address = c("567 23rd St S, Arlington, VA 22202",
                                         "3028 Wilson Blvd, Arlington, VA 22201",
                                         "4238 Wilson Blvd, Arlington, VA 22203",
                                         "4238 Wilson Blvd Ste. 1180, Arlington, VA 22203",
                                         "2900 Columbia Pike, Arlington, VA 22204",
                                         "2915 Wilson Blvd, Arlington, VA 22201"),
                             Ask_Angela = NA) %>%
  dt_mutate(OBJECTID = length(x = geometry$OBJECTID) + 1:nrow(x = .))

# have to improve the below
#missing <- rbind(not_accredited, missing_in_api)

missing_in_api <- missing_in_api %>%
  cbind(map_df(.x = missing_in_api$Address, .f = geocode)) %>%
  setnames(old = "lat", new = "Y") %>%
  setnames(old = "lng", new = "X")

geo_data_complete <- rbind(geometry, missing_in_api, fill = TRUE)

licenses <- dbReadTable(conn = conn,
                        name = "abc_licensees")

geo_data_complete <- geo_data_complete %>%
  dt_mutate(address = str_to_lower(string = Address) %>%
              str_remove_all(pattern = "[\\s+|\\+]"),
            restaurant = str_to_lower(string = Restaurant) %>% 
              str_remove_all(pattern = "\\s+"),
            geo_key = str_sub(string = Address, start = 1L, end = 6L))

licenses <- licenses %>%
  dt_mutate(Add1 = str_to_lower(string= Add1) %>%
              str_remove_all(pattern = "\\s+"),
            TradeName = str_to_lower(string=TradeName) %>%
              str_remove_all(pattern = "\\s+"),
            license_key = str_sub(string = Add1, start = 1L, end = 6L))

#MAKE UNIQUE KEY COL FOR BOTH DATASETS BEFORE MERGE
str_c
geo_data_complete$unique_key <- paste(geo_data_complete$geo_key,geo_data_complete$restaurant)
licenses$unique_key <- paste(licenses$license_key,licenses$TradeName)

licenses <- licenses %>%
  dt_select("TradeName","Add1","unique_key","LicStatus_StatusDesc", "PrivDesc")


license_final <- merge(geo_data_complete, licenses, by.x = 'unique_key',by.y = 'unique_key', all.x = TRUE, no.dups = TRUE)
#license_final <- license_final[c("unique_key","lat","lng","restaurant","address","ask_angela","dist","LicStatus_StatusDesc")]

dbWriteTable(con = conn,
             name = 'vabc_arlington_restaurants',
             value = license_final,
             row.names = FALSE,
             overwrite = TRUE)

dbDisconnect(conn = conn)

```






