---
title: "Raw Data Table Creation"
author: "Kateryna Savchyn"
date: "5/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Sources Description

### Arlington County Police Incident Log

Source: https://data.arlingtonva.us/dataviews/225891/police-incident-log/
Last Updated: 05/30/2019

### ABC Virginia Hearing and Appeals: Final Decisions

Source: https://www.abc.virginia.gov/enforcement/hearings-and-appeals/final-decisions/
Last Updated:07/2017 - 06/2018

### ABC Virginia Licensee Data

Source: https://www.abc.virginia.gov/licenses/licensee-search-staging
Date Pulled: June 2019
Last Updated: April 2019

## Install Packages

```{r load packages, message=FALSE, warning=FALSE}
library(DBI)
library(httr)
library(jsonlite)
library(data.table)
library(tidyverse)
library(RPostgreSQL)
library(gdata)
library(openxlsx)
library(xlsx)
library(tidyverse)
```

```{r pull+create incidents table}

crime_incidents <- function(arlington_api_key) {
  output = str_c('https://api.data.arlingtonva.us/api/v2/',
                        'datastreams/POLIC-INCID-LOG-19589/data.csv/?auth_key=',
                        arlington_api_key) %>%
    GET() %>%
    content(as = 'text', encoding = 'UTF-8') %>%
    read_csv() %>%
    mutate(firstReportDtm = as.POSIXct(x = firstReportDtm, tz = 'EDT'),
           lastReportDtm = as.POSIXct(x = lastReportDtm, tz = 'EDT')) %>%
    data.table() %>%
    setnames(old = 'reportNbr', new = 'id') %>%
    setnames(old = 'offenseDsc', new = 'description') %>%
    setnames(old = 'locationName', new = 'location') %>%
    setnames(old = 'latitudeCrd', new = 'latitude') %>%
    setnames(old = 'longitudeCrd', new = 'longitude') %>%
    setnames(old = 'firstReportDtm', new = 'start') %>%
    setnames(old = 'lastReportDtm', new = 'end')
 conn <- dbConnect(drv = PostgreSQL(),
                    dbname = "acpd",
                    host = "postgis",
                    port = "5432",
                    user = Sys.getenv("db_userid"),
                    password = Sys.getenv("db_pwd"))
  dbWriteTable(con = conn,
               name = 'incidents',
               value = output,
               row.names = FALSE,
               overwrite = TRUE)
  on.exit(dbDisconnect(conn = conn))
  }


#crime_incidents(arlington_api_key = "a8c777094627e4dd07453fa1fd7676ed613eaa26")

```

```{r pull+create violations table, message = FALSE, warning = FALSE}

violations = function() {
  # download 3 data since 2015 - differing file names necessitate exact link embedded in function
    download.file("https://www.abc.virginia.gov/library/enforcement/other-documents/finalboardorders_july2015-june2016.xls?la=en", destfile = "~/acpd/data/acpd/original/violations-1.xlsx")
    download.file("https://www.abc.virginia.gov/library/enforcement/other-documents/fy17-final-board-order-spreadsheet.xlsx?la=en", destfile = "~/acpd/data/acpd/original/violations-2.xlsx")
    download.file("https://www.abc.virginia.gov/library/enforcement/other-documents/finalboardorders_july2017-june2018.xls?la=en", destfile = "~/acpd/data/acpd/original/violations-3.xls")
    
  # bind datasets
    v1 <- read_xls("~/acpd/data/acpd/original/violations-1.xls")
    v1 <- data.frame(v1[,1:25])
    v1 %>% mutate_if(is.factor, as.character)
   
    v2 <- read_excel("~/acpd/data/acpd/original/violations-2.xlsx")
    v2 <- v2[,1:25]
    v2 %>% mutate_if(is.factor, as.character)
    names(v2) <- names(v1)
    
    v3 <- read_excel("~/acpd/data/acpd/original/violations-3.xls")
    v3 <- data.frame(v3[,1:25], stringsAsFactors = FALSE)
    v3 %>% mutate_if(is.factor, as.character)
    names(v3) <- names(v1)
    
    violations <-rbind(v1,v2,v3)
    
    conn <- dbConnect(drv = PostgreSQL(),
                  dbname = "acpd",
                  host = "postgis",
                  port = "5432",
                  user = Sys.getenv("db_userid"),
                  password = Sys.getenv("db_pwd"))

    dbWriteTable(con = conn,
              name = 'violations',
              value = violations,
              row.names = FALSE,
              overwrite = TRUE)

    dbDisconnect(conn = conn)
  
}
  

#violations()
```


```{r pull and create license table}
licenses <- function(){

  download.file("https://www.abc.virginia.gov/library/licenses/other-documents/valicapril2019.xlsx?la=en", destfile="~/acpd/data/acpd/original/licenses.xlsx")
  license_data <- openxlsx::read.xlsx("~/acpd/data/acpd/original/licenses.xlsx")

  conn <- dbConnect(drv = PostgreSQL(),
                      host = "postgis",
                      port = "5432",
                      user = Sys.getenv("db_userid"),
                      password = Sys.getenv("db_pwd"))
  
  dbWriteTable(con = conn,
                 name = 'licenses',
                 value = license_data,
                 row.names = FALSE,
                 overwrite = TRUE)
  dbDisconnect(conn = conn)
}

#licenses()

```


