---
title: "Similarity_Indexing"
author: "Kateryna Savchyn"
date: "7/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Bring In Data + Clean

```{r packages, message=FALSE}
library(here)
library(readxl)
library(maditr)
library(tidyr)
library(stringr)
library(dplyr)
library(hutils)
```

```{r sim data}
dat <- here('data', 'acpd', 'Similarity Matrix', 'similaritymatrix.xlsx')
sim <- read_excel(dat) 
# break list of categories into multiple columns
sim$Category_ns <- ''
sim$Category_ns <- str_trim(sim$Category) 
# all unique categories, to check
# cats <- paste(sim$Category_ns, collapse=',' )
# uniq_cats <- unique(unlist(strsplit(cats, ","))) %>% str_trim()

sim_sep <- separate(sim, col = Category_ns,into = c('A','B', 'C'), sep = ',', remove = FALSE) %>% data.table()
sim_n <- drop_empty_cols(sim_sep)
# dcast the 3 cols 
sim1 <- dcast(sim_n, Restaurant + Address ~ A, function(x) 1, fill = 0)
names(sim1) <- str_trim(names(sim1))
sim2 <- dcast(sim_n, Restaurant + Address ~ B, function(x) 1, fill = 0)
#standardize duplicate names by adding the dupe counts together
names(sim2) <- str_trim(names(sim2))
names(sim2)[3] <- "Bars2"
names(sim2)[5] <- "Italian2"
names(sim2)[6] <- "Pizza2"
sim2$Bars_f <- sim2$Bars + sim2$Bars2
sim2$Italian_f <- sim2$Italian + sim2$Italian2
sim2$Pizza_f <- sim2$Pizza + sim2$Pizza2
sim2[ ,c('Pizza', 'Pizza2', 'Bars', 'Bars2', 'Italian', 'Italian2')] <- list(NULL)
sim3 <- dcast(sim_n, Restaurant + Address ~ C, function(x) 1, fill = 0)
names(sim3) <- str_trim(names(sim3))
names(sim3)[4] <- "Salad2"
sim3$Salad_f <- sim3$Salad + sim3$Salad2
sim3[ ,c('Salad', 'Salad2')] <- list(NULL)

#filter to cast the yes/no attributes
sim_f <- merge(sim1, sim2, by = c('Restaurant', 'Address'))
sim_f <- merge(sim_f, sim3, by = c('Restaurant', 'Address'))

%>% dt_filter(Yes_No == 'Yes' | Yes_No == 'No')
# cast the yes/no then merge back with the list of 


```

